[build-system]
requires = [
    "setuptools>=42",
    "setuptools_scm[toml]>=3.4",
    "wheel",
]

[tool.black]
line-length = 79

[tool.isort]
force_single_line = true
known_third_party = [
    "pytest",
]

[tool.setuptools_scm]
