data_path: examples/house-prices-advanced-regression-techniques/train.csv.gz
label_col: SalePrice
model_path: examples/house-prices-advanced-regression-techniques/model.pkl
model_source: optgbm.sklearn.OGBMRegressor

# Optional
data_kwargs:
  index_col: Id
params:
  n_estimators: 100_000
  n_trials: 100
  n_jobs: -1
  random_state: 0
