version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.6.8
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install .
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            python setup.py test
          no_output_timeout: 1h
