data_path: examples/train.csv.gz
label_col: Survived
model_path: examples/model.pkl
model_source: optgbm.sklearn.OGBMClassifier

# Optional
data_kwargs:
  dtype:
    Age: float32
    Embarked: category
    Fare: float32
    Pclass: category
    Parch: float32
    Sex: category
    SibSp: float32
  index_col: PassengerId
  usecols:
    - PassengerId
    - Age
    - Embarked
    - Fare
    - Pclass
    - Parch
    - Sex
    - SibSp
    - Survived
params:
  n_trials: 100
  n_jobs: -1
  random_state: 0
