data_path: examples/ghouls-goblins-and-ghosts-boo/train.csv.gz
label_col: type
model_path: examples/ghouls-goblins-and-ghosts-boo/model.pkl
model_source: optgbm.sklearn.OGBMClassifier

# Optional
data_kwargs:
  index_col: id
params:
  n_estimators: 100_000
  n_trials: 100
  n_jobs: -1
  random_state: 0
