data_path: examples/bike-sharing-demand/train.csv.gz
label_col: count
model_path: examples/bike-sharing-demand/model.pkl
model_source: optgbm.sklearn.OGBMRegressor

# Optional
data_kwargs:
  dtype:
    season: category
    weather: category
  index_col: datetime
  na_values:
    windspeed:
      - 0.0
  parse_dates:
    - datetime
  usecols:
    - datetime
    - atemp
    - holiday
    - humidity
    - season
    - temp
    - weather
    - windspeed
    - workingday
    - count
params:
  n_estimators: 100_000
  n_trials: 100
  n_jobs: -1
  random_state: 0
