data_path: examples/titanic/train.csv.gz
label_col: Survived
model_path: examples/titanic/model.pkl
model_source: optgbm.sklearn.OGBMClassifier

# Optional
data_kwargs:
  dtype:
    Pclass: category
  index_col: PassengerId
  usecols:
    - PassengerId
    - Age
    - Embarked
    - Fare
    - Pclass
    - Parch
    - Sex
    - SibSp
    - Survived
params:
  n_estimators: 100_000
  n_trials: 100
  n_jobs: -1
  random_state: 0
